### ISSUE TITLE
Bump go mod dependencies

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-operator#14]
Some of the dependencies of the operator have new versions that are fixing (low) security vulnerabilities ( https://github.com/rancher/elemental-operator/security/dependabot ).

We should check if we are affected and we can bump to at least a patch version to address those.

**Comment by Itxaka** [comment]
> Confused Deputy in Kubernetes

Not affecting us, this is a kubernetes installation issue and configuration of the kube-apiserver. Also open since September 2021 with no fix as it seems to be a low priority issue and not very important. Dismissed.

> Clarify `mediaType` handling 

Patch version available, PR created: https://github.com/rancher/elemental-operator/pull/26

>  OCI Manifest Type Confusion Issue

Minor version availabel, PR created: https://github.com/rancher/elemental-operator/pull/27

**Comment by Itxaka** [comment]
Both PRs merged
