### ISSUE TITLE
see how the operator scales and works in parallel

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-operator#149]
Part of #147 

Questions to answer
- can multiple operators be run in parallel or do they clash ?
- ...

**Comment by Itxaka** [comment]
currently we can approach this in 2 ways. 1 operator in different namespaces or multiple operators in 1 namespace.

Will prepare tests to run both scenarios

**Comment by Itxaka** [comment]
ummm, multiple namesapces seems a bit more complicated due to the use of `ApiService` which is cluster wide and only accept one runnig at a time.

Which kind of makes sense...I mean, you cannot have 2 different things listening to the same cluster path :)

**Comment by Itxaka** [comment]
https://github.com/rancher/elemental-operator/pull/150 in order to allow setting replicas, which is necessary for horizontal scaling

**Comment by Itxaka** [comment]
yep, killing the pod that its answering all requests makes the other pod pick the requests. I guess we are missing something in our operator serve because this help with resiliency but not with scalability

**Comment by Itxaka** [comment]
Yeah we may need to investigate further into the apiservice and why no other pods pick that.

AFAIK it works by setting a websocket tunnel in rancher to the application using steve aggregation server, so maybe its due to that? So we cna directyl go to the RANCHER_SERVER_URL/elemental and access our application. 

But I dont see anything more configurable in the apiservice, and that is the way of getting a full cluster url without dealing with ports and services :/

Probably should check with someone that knows about this on the rancher team

**Comment by agracey** [comment]
I wonder if Steve doesn't have a way to aggregate across replicas?

**Comment by agracey** [comment]
I also wonder how this works when there are multiple Rancher servers running?

**Comment by Itxaka** [comment]
> I wonder if Steve doesn't have a way to aggregate across replicas?

I mean, it look like it actually does, I can see 2 pods connecting to the steve aggregation server, so the tunnels are in there but traffic hitting at the /elemental path only end up in one of the pods.

I wonder if its the last/first one to setup the tunnel the one that gets all the traffic? Or there is no 1 to many relationship in there. With ws should be possible to have a ws endpoint and several clients connected and getting the same info. But that would lead to several pods working on the same request.

Gonna try to scale up and down the deployment to see how the steve server behaves with several clients. I may be possible that we are not using it properly.

In any case, I think steve was meant to be able to connect directyl from the "main" cluster to the rest of the clusters managed by rancher directly so it may as well not be contemplated in its design.

>I also wonder how this works when there are multiple Rancher servers running?

I have 0 idea, nor have I found any examples of using `ApiService` CRDs anywhere, thus why I would probably need a 1on1 with someone that knows about this. Following the code is also a bit difficult with all the abstraction behind everything :D

I would have expected a `Service` instead so you could it the clusterIP:PORT and get directly to the deployment. No idea why it was done this way. I mean, its cooler yeah and easier but...

**Comment by Itxaka** [comment]
Interestingly enough, it seems like upscaling the rancher pods are needed in order to upscale the operator. Testing with 3 rancher replicas and 3 operator replicas results in the http calls being sent to different pods.

Weirdly enough, I can only get requests to 2 pods with 3 replicas...

**Comment by Itxaka** [comment]
I got all replicas to answer http requests by increasing the number of physical nodes to 4 and replicas of rancher to 4.

Looks like there is a direct relation between the rancher replicas and the operator replicas, they have to match. Im guessing that this is due to the tunnel stuff?

In any case, scaling horizontally is possible with this, as long as the rancher replicas are the same number as the operator replicas.

Now to do any kind of benchmark we would need like real hardware to test this properly. At least a cluster with rancher with 3 nodes and an extra node to run the benchmark from. That way we can scale the operator from 1 to 2 to 3 and compare the raw number of requests it can deal and if its linear.


Note that all this tests are done via requests to an unauthenticated endpoint to test the viability, this is not the full workflow. For that we should create a node simulator or something similar that can hit the registration endpoint so the operator creates the inventory, which would be heavier than this.

But I consider this card done, we can scale horizontally.

**Comment by davidcassany** [comment]
Cool! thanks for all these insights, yes I agree, this is enough for now, next step would actually plan/design some sort of benchmark tests which is not the intention of this card as this looks like an epic to me.

**Comment by Itxaka** [comment]
Yes, EPIC sounds good indeed, this requires of work and planning.

**Comment by kkaempf** [comment]
@agracey - jfyi
