### ISSUE TITLE
Consider removing machineName from registration

### ISSUE THREAD

**Issue by alexander-demichev** [rancher/elemental-operator#189]
Registration exposes a field called `machineName` https://github.com/rancher/elemental-operator/blob/main/pkg/apis/elemental.cattle.io/v1beta1/registration.go#L38, if registration is intended to be used by multiple machines we shouldn't allow configuring individual resources. Using defaults based on UUID https://github.com/rancher/elemental-operator/blob/main/pkg/server/register.go#L280 makes much more sense. We can also reflect the hostname in the machine inventory status.

**Comment by fgiudici** [comment]
I see your point... anyway  the `machineName`  could be expanded with smbios data, where the user can put UUID, serial number, etc. Some customers may have their own policy for managing host names (at the end that would be the host name of a node in their cluster).
I would generalize the issue to ensuring the hostname is unique by some means ( e.g., by appending something to the `machineName`if it is already used or even just fail the registration... if you set an hostname, it is up to you to ensure it is unique). Note that removing the machineName would be still one option to ensure the hostname is unique 😄

**Comment by ldevulder** [comment]
I already wrote this elsewhere but I add it here too:
IMHO we need to be able to allow users to user their own hostname. Some companies have naming convention. Where I worked before it wasn't allowed to boot server with non-allowed hostname.
This is why such option is needed I think.

**Comment by kkaempf** [comment]
Users should be able to influence the `machineName` in order to make it recognizable. The current default is pretty un-recognizable (when using KVM machines).
I currently see names like `m-2518a87f-2562-40d2-bbdd-21d220db7332` and `m-e6e03735-091f-450a-9d15-8702c6d6c4be` in the `machineInventories` overview page - not very useful for humans.

**Comment by Itxaka** [comment]
wait, has something happened with this? machineName is not only configurable but its also interpolated with smbios data? so nothing prevents your from configuring it as you wish?  https://github.com/rancher/elemental-operator/blob/main/pkg/server/register.go#L309

> We can also reflect the hostname in the machine inventory status.

Why not use labels? Seems much more flexible and allows us to use selectors with those labels easily for upgrades for example.

> Note that removing the machineName would be still one option to ensure the hostname is unique

We cant? Its used for generating the `inventory.name`. Otherwise you cant configure your template for the final name that each machine gets? Why would we remove a feature after all the steps that we had to hoop on to get it in (hint: smbios data was `required` as a feature for this reason)

> I currently see names like m-2518a87f-2562-40d2-bbdd-21d220db7332 and m-e6e03735-091f-450a-9d15-8702c6d6c4be in the machineInventories overview page - not very useful for humans.

That is because either you are not setting the machineName in the registration or using the default? Nothing is preventing you from setting it to `my-kvm` ? Although good luck with any cluster in which the names have the same hostname lol

Its not our job to set a default that its nice, its our job to set a default that its unique and doesn't clash with any other machine no matter how many times the same registration is used. Using the machine uuid its the best we can do that guarantees that.



What is the real problem here? what is really needed? why its machineName suddenly needed to be unique? The reason it can be reused its that its kind of a template, then every machine using that registration would fill the `inventory.Name` with its own data. Maybe a rename to MachineNameTemplate is just what is required?

**Comment by Itxaka** [comment]
I could understand expanding it to inject the smbios data with even more data, like network addresses for example, but otherwise how are you expected to name a machine in which a iso is gonna be inserted and nothing else touched? We need to use the smbios data + maybe other data acquired in the running system to generate a proper valid inventory. And as 1 inventory = 1 machine, reusing the same name (with caveats) for the hostname makes sense. We dont want to have 4 different places where the hostname is set as we did before because not only it was a mess, its was impractical to maintain and lead to issues with the nodes rebooting and changing hostnames, rke/k3s deployments not rebooting correctly due to node name changes and crap like that. Basically a race condition on hostname setting, which in the end is affected by the machineName.

**Comment by ldevulder** [comment]
> Although good luck with any cluster in which the names have the same hostname lol

Yes, that's why having a way to set a custom but unique `machineName` is good. And it is possible (see my test: https://github.com/rancher/elemental-operator/issues/190#issuecomment-1266935412)

> What is the real problem here?

The initial issue was this "bug": https://github.com/rancher/elemental-operator/issues/190, which in fact is not. Simply because I used the "old" way to set a hostname. After the discussion came to the current issue and also the fact that we need a way to allow users to create their own template that can be easily configured in `MachineRegistration` and that also can ensure that the generate `machineName`/hostname is unique. And it's finally working as expected.

My concern was mainly to ensure that we can allow users to set their hostname as they want. As most company have a naming convention.

**Comment by alexander-demichev** [comment]
Looks like `machineName` can be used for multiple machines and it works as expected. We can close the issue.
