### ISSUE TITLE
[Epic] build-image API

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-operator#207]
Now that rancher/elemental#365 is done, we need to bring "injecting the registration yaml into the pre-build ISO" (aka "ISO building") to the UI.

The UI should have a "Download ISO" button on its `machineRegistration` page.

This requires API support in the operator.

This API needs to
- handle download and caching of the pre-built ISOs
- given a `machineRegistration` and an ISO-image, create a final ISO
- allow the UI to download the ISO

Note: There's no need to store/cache the final ISO. Injecting the registration yaml should only take seconds.

**Comment by Itxaka** [comment]
2.7.0 is on one month. Are we sure this should be targeted there? Feels like an EPIC to me and it should be properly implemented. The api, the mechanism behind it, where to store, where to build the iso and store temporarily to inject the registration, how to select the base image to buld the iso from, the caching, etc.etc.etc.etc.

Plenty of stuff in this card IMO, we cant rush it in one month (I mean, we can but then we have to support whatever we ship....)

**Comment by fgiudici** [comment]
Notes on ISO API design (draft)

2 REST API to expose:
1.  To trigger ISO build
2. To retrieve the status of the ISO build status (and the URL from which to download)

The URLs should include the token (so it will automatically be bound to the MachineRegistration and will provide the same security as to download the registration yaml, i.e., the knowledge of the token)

### 1. trigger ISO build
The API should receive in input the base OS (base ISO url?), if not provided will use the latest teal ISO released.
The build ISO process should run in a separate workload (POD).
The required steps to be performed are:
- start the new POD to run the ISO build process
- allocated required storage to download the base ISO and store the composite one (emptyDir volume)
- retrieve the base ISO and the reg.yaml
- produce the final ISO

### 2. expose ISO build status
Return the status of the ISO build (e.g., downloading base ISO, building ISO, ready, ...). When the composite ISO is ready, expose and return the download URL.

**Comment by kkaempf** [comment]
How do we know which base ISO urls are available ?
We probably don't want to search a registry everytime. And registries might still have outdated (and unsupported) versions available.
And how to support custom-built ISOs ?

**Comment by davidcassany** [comment]
> How do we know which base ISO urls are available ?

I'd say this is out of scope now, we have not matured the channel concept yet and this kind a coupled to the delivery infrastructure. For later, but I would couple it to the `ManagedOSVersionChannel`, probably we can include an optional iso reference into that resource. So, assuming we ever produce our own ManagedOSVersionChannel data, each OS image could also be tied to an ISO release.

Probably this is something to start caring about, how to define and deliver upgrades via a ManagedOSVersionChannel?

> And how to support custom-built ISOs ?

I am wondering if this should be part of the registration yaml data. I mean, since the OS to install can be set there I'd say the version if any, should be stated there. In the registration includes the option of setting an specific docker image, I am wondering if it would make sense setting some sort of mechanism to build the ISO from scratch if a custom image is provided. The difference is that building from scratch is CPU intense process and it can take few minutes, while simply adding the registration yaml to an already existing ISO takes seconds if the ISO is already in the host. In terms of elemental-operator code the wouldn't difference any difference on one procedure or the other and the pods to inject or build the iso would the same, so with such a design this is would be a low hanging fruit feature.

**Comment by fgiudici** [comment]
Basically, we have to expose two APIs: one for triggering the ISO build (BUILD API) and one for retrieving the status of the build process and the final download URL when done (STATUS API).

Let's split this EPIC in 3 iterations:
1. First iteration: expose the APIs
  [a] add a base ISO url field (in MachineRegistration), expose the BUILD API in the operator, do a PoC build inside the operator (quick and dirty 😅 ), expose the STATUS API
2.  Second iteration: verify the APIs and do the ISO build the right way:
  [a] validate the BUILD API and STATUS API format with the UI side
  [b] rework the ISO build to have it right: on a child POD, using a storage volume (emptyDir?)
  [c] define what is the default base ISO (if not provided in the url field from 1.a)
3.  Third iteration:  improvements/refinement
  [a] explore  options for retrieval of ISO from a channel
