### ISSUE TITLE
Default `eject-cd` to true ?

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-operator#208]
$subject says it all :wink:

**Comment by Itxaka** [comment]
We may not need to, now that we are setting the proper efi entry, on reboot it will pick it up automatically on decent EFI systems.

Now, as EFI is an "standard" and its implemented wildly different in the boot order stuff, I dont recommend that we drop it completely, otherwise it will be dropped as it was mainly added due to the bios constraints (no way on bios to select the default entry to boot from)

**Comment by agracey** [comment]
I don't even know how to test this 😆 I guess we could try again in the Metal^3 environment and see what happens? 

I'm comfortable calling this done until we see it be an issue again on non-weird-hacked-together setup.

**Comment by kkaempf** [comment]
Closing for now. Thanks all !
