### ISSUE TITLE
Allow for setting static IP address in MachineInventory

### ISSUE THREAD

**Issue by agracey** [rancher/elemental-operator#23]
While this can be done with manually editing the system-agent "plan", it would be very useful to allow for setting a static IP address just by changing a field in the MachineInventory (even if the underlying data path is the same).

We would then likely need to have a status field stating that it's waiting for a change to be validated that goes back to "ready" after the application gets set and communicated back to the operator.

**Comment by agracey** [comment]
This should have a UI component to it as well

**Comment by kkaempf** [comment]
Uh, oh, that probably needs some further brainstorming.

Right now, `machineInventory` is "write-only" from a client's perspective. The request above would make it "read-write".

I'm also not convinced that Elemental should do (such type of) network configuration, which typically is handled _outside_ of a system (by the network equipment).
Given that we consider nodes as "cattle", they all should just do DHCP and leave the rest to the routers/switches/etc. they're connected to.

**Comment by agracey** [comment]
We think we might be ok with the plan method that we are using currently for the demo. But let’s think through scenarios after my upcoming PTO

**Comment by Itxaka** [comment]
This overcomplicates things soooo much.

How would this behave if there is a cluster running with some IP configured already and suddenly the machineInventory changes that ip? We would need to redeploy the bootstrap plan to reconfigure the whole thing, tear down any deployment already on the machine and redeploy the whole thing. Pretty easy to fuck up stuff around with that, especially with our currentl knowledge of the full deployment workflow, Im not even sure if its possible. I mean, just a hostname change broke the whole cluster due to not cleaning the old deployment with a different hostname and you want an IP change which is much more delicate? yikes...


IMHO I agree with @kkaempf here, machines are cattle, they are dumb and they do the less work possible, the configuration has to come from a different place, network by network, deployment by rancher.  they are dumb and should be dumb, start, install, boostrap, deploy cluster and done. Not touching them anymore.

**Comment by kkaempf** [comment]
closing as rejected
