### ISSUE TITLE
Provide alternative to TPM/vTPM/emulatedTPM

### ISSUE THREAD

**Issue by abonillabeeche** [rancher/elemental-operator#235]
**Describe the solution you'd like:**
Utilizing the System UUID as an option vs requiring the use of TPM for a system identifier.

This will enable deployments
- If the hardware does not support TPM
- If the virtualization platform does not support TPM
- If TPM is not enabled or not preferred/incompatible.

**Comment by Itxaka** [comment]
@fgiudici I think you are the most experienced with the TPM auth back and forth between the cleint and operator, do you think it would be possible to do the same with a different identifier? Maybe using the uuid of the machine? Maybe using the uuid as a seed for the tpm emulation?

**Comment by fgiudici** [comment]
The TPM module is used to securely identify the on-boarding machine.
TPM emulation was mainly introduced for testing purposes and does not provide secure identification of the registering machine.
We can introduce other type of authentication for machine identification (e.g., a secret and/or a UUID), they wouldn't anyway match the security of what we can do with TPM.
As long as we also introduce a way to enforce machine auth for registration in the operator ( via TPM, UUID, ...) I don't have any concern to allow registering without TPM.

**Comment by agracey** [comment]
It would also be helpful to annotate the MachineInventory associated with how the machine authenticated itself. This would allow an admin to quickly confirm their security posture.

**Comment by fgiudici** [comment]
Dropping a note here about TPM emulation: when emulated-tpm-seed is set to 0 (or when it is not specified) in the MachineRegistration, we end up to use a seed of 1 during client registration.
Enforcing a seed of 0 (manually editing the registration yaml and putting 'emulated-tpm-seed: 0') , will perform TPM emulation using random keys. While this would be the way to allow multiple hosts without TPM to use the same ISO to register to the elemental operator, this actually doesn't work due to an issue in the tpm library we rely on (see https://github.com/rancher-sandbox/go-tpm/issues/6).
While we can fix the library, I think there is no reason to use TPM to register if the machine has no TPM: using a random key that we will throw away after registration makes no sense. 
So, better to invest in an alternate authentication method (e.g., free enrollment), to be tracked in the MachineInventory through a label and/or an annotation.

**Comment by agracey** [comment]
For the short term, would it make sense to have `-1` map to using some portion of a unique-ish identifier (serial number?) as the bits for the seed?

**Comment by fgiudici** [comment]
> This is weird because with my patch at #282 I was able to boot, enroll and deploy a cluster into a node with a random tpm seed... what are the issues that you are seeing? I could not find any!

#282 is perfect 🚀 
I mean, the original library allows random TPM keys generation (not binded to a unique seed) putting 0 as seed. In that case, it will not work.
Your patch randomize the initial seed, and that works pretty well! 🎉

**Comment by Itxaka** [comment]
This is kind of done already with the random TPM seed based of the UUID of the machine?
