### ISSUE TITLE
Unable to fetch principal info on freshly provisioned cluster

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental-operator#310]
### Issue

After deploying a simple cluster with Elemental I have this issue in `Cluster Members`:
![Screenshot from 2022-12-20 11-00-46](https://user-images.githubusercontent.com/25102165/208639932-6409f5d5-76d7-4273-bf63-ca2d57f6a82c.png)

I'm also unable to deploy an application with Helm Chart in `Apps/Charts`, I have a blank screen like this:
![Screenshot from 2022-12-20 11-03-14](https://user-images.githubusercontent.com/25102165/208640183-af028780-e83e-4ed5-a8ac-75f01073bd62.png)

After some checks I found these errors in rancher's logs:
```
# kubectl logs -f -n cattle-system -l app=rancher
2022/12/20 09:30:47 [ERROR] error syncing 'c-m-2qhcwxfr/creator-cluster-owner': handler mgmt-auth-crtb-controller: users.management.cattle.io "system:admin" not found, requeuing
2022/12/20 09:30:55 [ERROR] error syncing 'p-kntm9/creator-project-owner': handler mgmt-auth-prtb-controller: users.management.cattle.io "system:admin" not found, requeuing
2022/12/20 09:30:55 [ERROR] error syncing 'p-hdt27/creator-project-owner': handler mgmt-auth-prtb-controller: users.management.cattle.io "system:admin" not found, requeuing
```

Looks like a permission/owner issue.

I found a workaround to this issue: go to `local` cluster, `More Resources`, `Cluster Provisioning`, `Clusters`, then select your newly created cluster (`cluster-k3s` in my case)  then `Edit Config`. In `Cluster Configuration` select `Member Roles`: you can see the `Unable to fetch principal info` error but you can also (re)add your `admin` user as a owner:
![Screenshot from 2022-12-20 11-28-17](https://user-images.githubusercontent.com/25102165/208645348-da5f923b-3087-49b9-a578-418e69e48c1e.png)

You can then delete the bad one. All will now work as expected. In fact it will work even if you keep the bad owner but in that case the `Cluster Members` list will be empty.

### How to reproduce this issue

Install the componment in this order:
- K3s (or RKE2)
- CertManager (latest version)
- Rancher Manager v2.7.0
- Elemental Operator (DEV version, v1.1.0-x)
- Elemental UI plugin

Then create the diffents Kinds from the CLI (I used `kubectl apply -f`):
- Cluster (K3s, only one node)
- MachineRegistration
- Selector

Then download the `registrationUrl` file and add it in a DEV ISO, then provisioned a node in the cluster.

I added `elemental-support` logs if this can help (before and after changing the cluster's owner).
[after_changing_owner-k3s-rancher-2022-12-20T121008+0100.tar.gz](https://github.com/rancher/elemental-operator/files/10267855/after_changing_owner-k3s-rancher-2022-12-20T121008%2B0100.tar.gz)
[before_changing_owner-k3s-rancher-2022-12-20T120717+0100.tar.gz](https://github.com/rancher/elemental-operator/files/10267856/before_changing_owner-k3s-rancher-2022-12-20T120717%2B0100.tar.gz)

**NOTE:** I also tried to add the UI plugin *BEFORE* configuring/provisioning the cluster with Elemental but this didn't change anything.

**Comment by kkaempf** [comment]
This happens with k3s _and_ RKE2 ?

**Comment by ldevulder** [comment]
> This happens with k3s _and_ RKE2 ?

Yes, I just tested and it happens if you try to provisioned K3s or RKE2. It also happens if Rancher Manager is installed ontop of K3s or RKE2 (the user who initialy had this issue installed RM ontop of RKE2).
And the workaround works also on RKE2 provisioned cluster.

**Comment by kkaempf** [comment]
I didn't encounter such problems when I last tested with
```
"Operator version 1.1.0, commit 76d2bb39, commit date 20221216"
```
🤔

**Comment by juadk** [comment]
> I didn't encounter such problems when I last tested with
> 
> ```
> "Operator version 1.1.0, commit 76d2bb39, commit date 20221216"
> ```
> 
> thinking

Did you use YAML files to create resources or you made it totally in the UI?

**Comment by kkaempf** [comment]
> Did you use YAML files to create resources or you made it totally in the UI?

All YAML

**Comment by ldevulder** [comment]
> All YAML

This issue happens with the UI.

**Comment by ldevulder** [comment]
I just checked and I still have the issue on Rancher Manager 2.7.0 with the latest version of elemental-operator.

**Comment by davidcassany** [comment]
I doubt there is an issue with Elemental here, probably it is not even a Rancher issue. About week ago I spent some time reproducing it and trying to debug it and I do believe we are missing some RBAC resources or simiar when creating a rancher cluster from a YAML using `kubectl`, after some attempts I could figure exactly what was missing. Rancher does not document cluster creations from yaml files anywhere I could find and, to my eyes, rancher-client is there for this reason, to allow rancher usage from the command line without having this sort of gitches. I have no experience with rancher-client, probably we should give it a look and try document our command line usage by using it rather than using `kubectl`. I am not very happy with the idea, but probably this is the way to avoid this sort of glitches and follow common and documented rancher practices.

My take on this issue is that we should reconsider our docs and do not document ourselves how to create rancher resources or, at most, reproduce some already documented procedure if this is direct and simple enough to prevent linking users to somewhere else.

Also the quick start guide should be reconsidered as soon the UI is in place. Shouldn't it be based on the UI? How are we going to document the UI?

@agracey @aalves08  do you envision the UI documentation?

**Comment by davidcassany** [comment]
I did another round of attempts to sort this out with some more satisfying results. I followed instructions from slack channel (kudos to @MbolotSuse ) to actually set kubectl to login as a rancher user (rancher token as auth method) and seams to better result. The error message is gone and the default user is included. At the end I believe the easier is to configure kubectl with the autogenerated kubeconfig for the local cluster (downloading it or copying it to clipboard already generates a token, it can be done by the top icons on cluster dashboard).

If all CRDs are then created using the autogenerated kubeconfig the resulting cluster was including the default member like a cluster created from the UI. However, at least in my env, I could not manage to install any chart from the UI. Probably this is problem on my setup, I did pile of different tests and my env pretty much resource limited (2GB per node)... Trying to install did not produce any error, but clicking install to any chart just resulted in an empty page with no feedback.

@ldevulder I am not sure this is the behavior you also saw in the past. Would you mind giving a try using the autogenerated kubeconfig to create all crds from yamls as in the quick start guide? I'd like to ensure another pair of eyes have the same behavior.

**Comment by fgiudici** [comment]
nice investigation!
so, if I understand it correctly, the issue seems that the user in the kubectl config we use (the one from the rancher cluster) is missing some auth on the resources created in the elemental cluster.
My wild guess would be that we miss a Role in the generated elemental cluster, which should be created by Rancher when deploying the cluster via rancher agent's plans 🤔

**Comment by davidcassany** [comment]
@ldevulder I can confirm that despite using the kube config from the local cluster to create a cluster from a yaml I cannot install any workload from the UI, something fails in that case. However if I edit the config of the created cluster as suggested in the workaround of this issue I can install workloads again without issues 🤷🏽‍♂️  Feels something else is missing to be fully compatible with the UI when creating CRDs using the `kubectl` command line tool 🤔 Gonna try to debug it again, since we are slightly further now I can see something else.

**Comment by agracey** [comment]
I wonder if it would be different using the rancher cli? Direct API access to the rancher cluster is technically not supported so we may be running up against unintended consequences of their design.

**Comment by kkaempf** [comment]
Moving to blocked for now.

We need to better understand Rancher provisioning.

There's also the question if we should add UI documentation to elemental.docs.rancher.com (and eventually drop the command line instructions 🤔 ) /cc @agracey

**Comment by kkaempf** [comment]
UI documentation task: https://github.com/rancher/elemental-docs/issues/57

**Comment by kkaempf** [comment]
Might be unsupported 🤔

**Comment by ldevulder** [comment]
Latest fix in: https://github.com/rancher/elemental/pull/751.
