### ISSUE TITLE
e2e: testing operator uninstall

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-operator#314]
We should test uninstallation of `elemental-operator`, esp. the removal of associated CRDs.

**Comment by ldevulder** [comment]
I manually tested on a freshly installed cluster with these versions:
```
OS version: openSUSE Leap 15.4
K3s version: v1.24.7+k3s1
Rancher Manager version: 2.7.0 (with Elemental UI plugin installed)
Operator version: 1.1.0-dev
Operator image:
image: registry.opensuse.org/isv/rancher/elemental/dev/teal53/15.4/rancher/elemental-operator/5.3:1.1.0
imageID: registry.opensuse.org/isv/rancher/elemental/dev/teal53/15.4/rancher/elemental-operator/5.3@sha256:62a6c5209455d916822846007b9add7ced7264e80d19d9030bbb6d3a264f865c
```

I was able to provision a K3s cluster with Elemental on one node without any issue. Then I tried to uninstall the operator.

Uninstallation ran well:
```
# helm uninstall -n cattle-elemental-system elemental-operator
release "elemental-operator" uninstalled
```

But after uninstallation I can still see Elemental resources, is it expected?
```
# kubectl get machineregistration -n fleet-default
NAMESPACE       NAME                                       AGE
fleet-default   machine-registration-worker-cluster-k3s   30m
fleet-default   machine-registration-master-cluster-k3s   29m

# kubectl get machineinventories -n fleet-default
NAMESPACE       NAME                                        AGE
fleet-default   node-55392308-8b8f-4a04-b3b9-6dc1eed55689   26m
```

But not all, for example `MachineInventorySelectorTemplate` is not visible:
```
# kubectl get MachineInventorySelectorTemplate -n fleet-default
Error from server (NotFound): Unable to list "elemental.cattle.io/v1beta1, Resource=machineinventoryselectortemplates": the server could not find the requested resource (get machineinventoryselectortemplates.elemental.cattle.io)
```
Again, is it expected?

And the weird things is after a re-installation of the operator, it goes well and the pod is running:
```
# helm upgrade --create-namespace -n cattle-elemental-system --install elemental-operator oci://registry.opensuse.org/isv/rancher/elemental/dev/charts/rancher/elemental-operator-chart
Release "elemental-operator" does not exist. Installing it now.
Pulled: registry.opensuse.org/isv/rancher/elemental/dev/charts/rancher/elemental-operator-chart:1.1.0
Digest: sha256:9120cd921a83bee0fe347e24f73e660fdf7b2f06971ba616e9fdec27e8c80e0f
NAME: elemental-operator
LAST DEPLOYED: Wed Dec 28 16:39:16 2022
NAMESPACE: cattle-elemental-system
STATUS: deployed
REVISION: 1
TEST SUITE: None

# kubectl get pod -l app=elemental-operator -A
NAMESPACE                 NAME                                  READY   STATUS    RESTARTS   AGE
cattle-elemental-system   elemental-operator-5b5fb6c54b-vtgbv   1/1     Running   0          13m
```

But I now have this error when I try to apply a MachineRegistration yaml file:
```
# kubectl apply -f machine-registration-master-cluster-k3s.yaml 
error: resource mapping not found for name: "machine-registration-master-cluster-k3s" namespace: "fleet-default" from "machine-registration-master-cluster-k3s.yaml": no matches for kind "MachineRegistration" in version "elemental.cattle.io/v1beta1"
```
No issue with the cluster or selector yaml files.

I added the operator logs if needed for analysis.
[k3s-rancher-2022-12-28T170335+0100.tar.gz](https://github.com/rancher/elemental-operator/files/10315106/k3s-rancher-2022-12-28T170335%2B0100.tar.gz)

**Comment by ldevulder** [comment]
I re-tested with the latest Dev version and I have the same behavior, some resources are delete and others aren't, for example `MachineRegistration` is still here:
```
kubectl get MachineRegistration -n fleet-default
NAME                                      AGE
machine-registration-master-cluster-k3s   24h
machine-registration-worker-cluster-k3s   24h
```

The weird and blocking thing is that if I try to manually delete a remaining `MachineRegistration` for example I have this:
```
$ kubectl delete MachineRegistration -n fleet-default machine-registration-worker-cluster-k3s
machineregistration.elemental.cattle.io "machine-registration-worker-cluster-k3s" deleted
```
But it hangs, the `delete` command is not finished and I have no bash prompt.

On the UI side I can see this:
![Image](https://user-images.githubusercontent.com/25102165/221870204-840b1d5c-927a-4a42-968d-6d22c0b44197.png)


If I reinstall the operator I can see that the stuck `MachineRegistration` is gone:
```
kubectl get MachineRegistration -n fleet-default
Error from server (NotFound): Unable to list "elemental.cattle.io/v1beta1, Resource=machineregistrations": the server could not find the requested resource (get machineregistrations.elemental.cattle.io)
```

And I can't apply a new `MachineRegistration`:
```
kubectl apply -f elemental-test/k3s/machine-registration-master-cluster-k3s.yaml 
Error from server (NotFound): error when creating "elemental-test/k3s/machine-registration-master-cluster-k3s.yaml": the server could not find the requested resource (post machineregistrations.elemental.cattle.io)
```

**Comment by davidcassany** [comment]
After some digging I realized the following:

* on `helm uninstall` there is a delete request to all elemental resources and to all elemental CRDs.
* The delete request is not handled by the elemental-operator controllers, they are stopped before.
* Machineregistration and machineinventory include finalizers preventing them to be removed on uninstall, they are just scheduled with deletion time stamp. Since the controller is no longer running there is no reconciling loop handling the finalizers and resources are kept scheduled for deletion.
* On reinstall the resources scheduled for deletion are reconciled by the just installed controllers, the finalizers are handled and resources deleted. Apparently the deletion of the CRD was also scheduled awaiting the deletion of all associated resources, hence when resource finalizers are cleared and resources deleted the CRDs are also deleted. At this point the new fresh installation is in an inconsistent and wrong state as some CRDs were deleted. It can be seen by listing elemental api-resources. At this point the solution is to uninstall and reinstall again.

To properly fix it we should better understand and handle uninstall process. How finalizers should be handled in those cases? How to ensure all resources are reconciled on uninstall?

Also a side note is that I don't think we need the mentioned finalizers as I don't see any special mandatory logic to handle them. With the current setup I believe it is enough with the owner references (we are already setting them). Said that I foresee finalizers being used in the future (as part of the reprovisioning story for instance), hence finding a way to handle them is something relevant.

**Comment by davidcassany** [comment]
To summarize I believe we have a couple options:

1. Get rid of all the finalizers in our CRDs. I think this is doable, as far as I aware we are not using them for anything mandatorty. That means dropping some little logic, less code. However we might need some finalizer in the future and end up here again.
2. Create a pre-delete hook in our helm chart to cleanup. That means creating a cleanup command in elemental-operator and execute it as a Job before the helm delete sequence. That is the sophisticated and flexible approach implying some extra code and extra complexity in our chart.

**Comment by ldevulder** [comment]
Reopen this issue to add the test in CI, as we have a fix now.
