### ISSUE TITLE
Chunked upload of machineInventory smbios data

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-operator#5]
(Was: elemental-installer to honor nginx's packet size limits rancher/elemental#137)

"we figured out that issue with the Bad Websocket on the ROS installer. NGINX ingress by default needs flags appended to allow for headers larger than 8k. The header we were sending (containing MachineInventory data) was ~17k. This could be a bit of an issue since it requires modifications to the default configuration of nginx ingress which both RKE1 and 2 default to."

See also: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#large-client-header-buffers

**Comment by Itxaka** [comment]
smbios data is no longer stored on the machine inventory. If this is a wanted feature it needs to be planned and properly developed, otherwise we will break nginx again or need to reconfigure the whole cluster nginx just for this data, which is not sued anywhere else now.

A proper use case should be presented on why is this data useful and what data of the whole 18Kb of text dump is necessary, otherwise its more of a problem than a feature.

**Comment by Itxaka** [comment]
this has arisen again, because we, for some reason, send the whole smbios headers to the server to have it template the machineName. This made sense before when we were storing the whole smbios data on the inventory, but now it makes no sense.

Templating should be done on the client and that final machineName sent as part of the registration or any other fields that we want to interpolate and template, not on the server.

**Comment by Itxaka** [comment]
argh, this wont be possible, as we already submitted the machine name as a temple, it needs to be done in the server :(

**Comment by fgiudici** [comment]
To workaround the issue, increase the maximum size of headers in the nginx-controller configmap.
`large-client-header-buffers: 4 64k` should work.
See https://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers

Setting `no-smbios: true` option in the MachineRegistration may help too

**Comment by kkaempf** [comment]
Well, sounds like two major problems in the code base we inherited ...
- Sending larger amount of data should be done with POST data, not in header.
- Creating an object (like `machineInventory`) should be done with a POST request.

Bottom line: This needs a larger rewrite :-(

**Comment by Itxaka** [comment]
cant be done on POST as we need a get to do the challenge/response workflow for TPM....

**Comment by Itxaka** [comment]
and there is also the issue with doing the auth+inventory creation in the same request and we dont continue with the registration unless the auth passes, and that HAS to be done in the same request, we cannot let the client check the tpm auth and then register the inventory :/

**Comment by Itxaka** [comment]
I got this to split responses: https://github.com/rancher/elemental-operator/pull/133

There is also the possibility of not getting all smbios data and only store what we think is proper but that leads down a rabbit hole of someone ask to add X and we need to update the list of accepted values....

**Comment by Itxaka** [comment]
Also got this to provide minimum smbios data https://github.com/rancher/elemental-operator/pull/134

**Comment by fgiudici** [comment]
Looking at the code, I think we can just leave the Authentication header, and if present and has a Bearer token inside, upgrade the connection to websocket (so "standard" curl request will still HTTP GET the cloud-init file with just the ca-cert and url).
All the smbios data than can flow via the websocket. Working on this, will take a while, in the meanwhile #133  and #134  should workaround the issue.

**Comment by fgiudici** [comment]
First step is to split the communication/channel part from the TPM authentication: let's leave the communication part all under the management of the elemental operator while the TPM should be demanded to the tpm package.
The communication protocol is unchanged at this stage (but after merge the plan is to add an easy follow-up patch to move smbios and labels from HTTP headers to actual websocket channel).
Related PRs:

- [ ] rancher-sandbox/go-tpm#5 
- [ ] #140 (server side)
- [ ] #141 (client side)
