### ISSUE TITLE
QA: test operator installation via marketplace

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-operator#551]
Make sure we can deploy the latest dev operator through the Marketplace.

**Comment by juadk** [comment]
Well, I did some manual tests and I was able to install dev operator from the marketplace but it needs some tweaks before:
1. Download the dev operator helm chart
2. Tweak it a bit to remove these annotations
 `catalog.cattle.io/rancher-version: '>= 2.7.0-0 < 2.9.0-0'` and `catalog.cattle.io/auto-install: elemental-crd=match` => will be fixed by https://github.com/rancher/elemental-operator/pull/563
3. Install chartmuseum to create a helm repo with a correct `index.yaml` file
4.  Add my custom repo to Rancher:


![Image](https://github.com/rancher/elemental-operator/assets/6025636/89f844db-3f8b-4c08-85f8-b3dcc3e88221)
5. Install the dev operator (1.4.0) through the marketplace


![Image](https://github.com/rancher/elemental-operator/assets/6025636/d2208e55-6ef0-4fe3-9ac3-8a5c85616036)
