### ISSUE TITLE
Rancher Marketplace install broken version

### ISSUE THREAD

**Issue by SanekP** [rancher/elemental-operator#617]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
docker run --privileged -d --name rancher -p 443:443 rancher/rancher
Install Elemental extension 1.3.0.
Click button  Install Elemental Operator  as it stated in documentation https://elemental.docs.rancher.com/quickstart-ui#install-the-elemental-operator
![image](https://github.com/rancher/elemental-operator/assets/5805351/65dfd7e7-8fde-460b-9964-8ec893f4eb30)
![image](https://github.com/rancher/elemental-operator/assets/5805351/70b8cd5f-7c07-4386-8b5e-8d6baf5d99b8)
Channel and tag have hints but not default values.
After successful deployment there are no OS Version Channels.

**What did you expect to happen:**
I expected to see default OS Version Channel and OS Versions.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Can be fixed by upgrade to latest version which is not available in rancher with resetting values:
> helm upgrade --install -n cattle-elemental-system --create-namespace elemental-operator-crds oci://registry.suse.com/rancher/elemental-operator-crds-chart --reset-values
> helm upgrade --install -n cattle-elemental-system --create-namespace elemental-operator oci://registry.suse.com/rancher/elemental-operator-chart --reset-values

**Environment:**

- Rancher version:
Rancher	v2.8.1
Dashboard	v2.8.0
Helm	v2.16.8-rancher2
Machine	v0.15.0-rancher106

**Comment by juadk** [comment]
Thanks for the bug, it should be fixed when the latest stable operator will be pushed into the marketplace (cc @fgiudici), it's in progress.
Anyway, we will make sure to validate that point.

**Comment by fgiudici** [comment]
The channel OS image that we need to fill in the Operator Chart values (values.yaml) is a container image with a channel.json file tracking the info and URLs of the actual OS images:
```
$ docker run -ti --rm --entrypoint cat registry.suse.com/rancher/elemental-channel:1.4.2 channel.json
[
{
    "metadata": {
      "name": "v2.0.2"
    },
    "spec": {
      "version": "v2.0.2",
      "type": "container",
      "metadata": {
        "upgradeImage": "registry.suse.com/suse/sle-micro/5.5:2.0.2",
        "displayName": "SLE Micro"
      }
    }
  },
  {
    "metadata": {
      "name": "v2.0.2-iso"
    },
    "spec": {
      "version": "v2.0.2",
      "type": "iso",
      "metadata": {
        "uri": "registry.suse.com/suse/sle-micro-iso/5.5:2.0.2",
        "displayName": "SLE Micro ISO x86_64"
      }
    }
  },
[...]

```
The main issue we have in the official Rancher marketplace is that we  need to mirror all the images and use relative URLs, so that by default the images are retrieved from docker.io and when instead running in a Rancher air gap environment, Rancher itself will take care of prepending all the container images in the chart with the private registry configured once and for all in Rancher.
This would not work for the Elemental channel image for two main reasons:
1. the channel OS image may  be changed by the user to select different OS flavors. It could be something coming from an arbitrary repo, e.g., [registry.suse.com](http://registry.suse.com/) pointing to different OS images. This means we want to allow the usage of an absolute path that should not be prepended with any other registry.

2. Moreover, if we mirror a default channel image (e.g., mirror-rancher-channel on dockerhub)  the air gap scenario would be broken, as the links inside the channel OS image point to the outside, i.e. to [registry.suse.com](http://registry.suse.com/).  Mirroring also the OS images for Rancher is not an option, as the OS we distribute are based on SLE, and cannot be published on dockerhub.

So, to me, the best solution is to have this OS channel image to be referenced as a full image URL, pointing directly to the OS repo: in this case [registry.suse.com/rancher/elemental-channel](http://registry.suse.com/rancher/elemental-channel)

Pull request is here: https://github.com/rancher/charts/pull/3491/ .

The CI fails because of the full channel OS image path in the values.yaml file (https://github.com/rancher/charts/pull/3491/files#diff-5a7f0329eeb172ef35782b9fc91ca5605f28a7b16e2583e33dbc1f648fb31f20).
Currently under discussion best way to address this issue.
