### ISSUE TITLE
recovery as machine inventory name after reset

### ISSUE THREAD

**Issue by juadk** [rancher/elemental-operator#646]
I was playing with my rancher / elemental lab using` machineName: ${System Data/Runtime/Hostname}` and when I reset the node, I saw that machine inventory got created with recovery name (see screenshot below)

![image](https://github.com/rancher/elemental-operator/assets/6025636/084d33f8-d515-4b99-b4a6-3a913882f285)

What will happen if we reset multiple nodes at the same time? There will likely be conflict because we cannot have multi-machine inventory with the same name... 

It might be fixed by https://github.com/rancher/elemental/pull/1249 but we will have to confirm it.

**Comment by juadk** [comment]
Well, I tested the patch and it mostly fixes my issue but we still have a corner case:
If you do not have a DHCP server and you use `machineName: ${System Data/Runtime/Hostname}`, when you reset a node, you will get the following: 
![image](https://github.com/rancher/elemental-operator/assets/6025636/28ba2a82-2fe8-49a5-a84a-7326b4c6d260)

And I tested the fix with a fake DHCP in libvirt:
```
  <ip address='192.168.122.1' netmask='255.255.255.0'>
    <dhcp>
      <range start='192.168.122.2' end='192.168.122.254'/>
      <host mac='52:54:00:2b:d0:50' name='myhostname' ip='192.168.122.5'/>
    </dhcp>
```
And I got:
![image](https://github.com/rancher/elemental-operator/assets/6025636/78db8c48-d982-497f-beb6-5230d257c958)

**Comment by fgiudici** [comment]
When a machine registers, if there is no MachineInventory tracking obj, a new one is created on the operator side.
The unique identifier used there comes from the Registration authentication: usually, it is the TPM hash.
The Name of the MachineInventory object is the hostname that will be set to the host later on (during k3s/RKE2 provisioning) and will not change anymore (till deletion of the MachineInventory at least).
When configuring the machineName from DHCP, whatever is the hostname of the host during the registration, that is what will end up as the Name of the MachineInventory (and so as the final static hostname on k8s provisioning).
On "normal" boot we set a transient hostname of the kind "Rancher-VWXYZ" when no static name is detected: the transient hostname will be replaced by the DHCP one if any, otherwise will act as a fallback.
We need to do the same during recovery: since from there during reset a new registration can start, we need to ensure that in case the hostname should be set from DHCP and there is no DHCP name provided we have a sane one (i.e., Rancher-VWXYZ").
