### ISSUE TITLE
Issue with latest SLE Micro 6 and loopdevice snapshotter

### ISSUE THREAD

**Issue by juadk** [rancher/elemental-operator#699]
When using loopdevice as snapshotter with latest SLE Micro 6, the system does not install. It loops on mount / unmount commands. It works with disabling selinux in grub.

## How to reproduce
Build dev ISO using loopdevice as snapshotter option in the machine registration file and create an elemental node from it.

We will add logs soon.

**Comment by ldevulder** [comment]
Here the logs from the failing Elemental installer: [elemental-register-install.log.gz](https://github.com/rancher/elemental-operator/files/14917051/elemental-register-install.log.gz)

**Comment by davidcassany** [comment]
I think this is finally fixed by building with docker engine again. I have seen few tests from Dev passing today in the manual workflow, leaving it open until next week. I'd close it then if this is not happening again. More over this was related to SELinux and given we have other SELinux cards this is likely to investigated and worked on other issues.

**Comment by juadk** [comment]
I can manually test it tomorrow and close it, if it's ok.

**Comment by kkaempf** [comment]
Did not appear again
