### ISSUE TITLE
Merge elemental-installer into elemental-operator

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-operator#7]
Merge elemental-installer code from https://github.com/davidcassany/ros-installer/tree/adapt_to_latest_elemental_env_vars (also including those two commits here https://github.com/davidcassany/ros-installer/compare/adapt_to_latest_elemental_env_vars...rancher-sandbox:ros-installer:main ) into the elemental-operator codebase:

- Port code and also CI workflows
- Manual QA
- Update docs
- Update OBS ( feel free to ping @kkaempf )

**Comment by davidcassany** [comment]
@mudler @kkaempf while digging the code started to have doubt regarding this task. A first I thought we were aiming to an additional  `installer` subcommand in `elemental-operator` binary, so being mapped to a single package in OBS that produces a single `elemental-operator` RPM. However we could also simply include the _elemental-installer_ (just rename and similar cosmetic changes) code into the [rancher/elemental-operator](https://github.com/rancher/elemental-operator) repository and then add an additional build target for the installer to produce an `elemental-installer` RPM as an `elemental-operator` subpackage in OBS. 

After seeing rancher/elemental#160 I thought that the latter might have more sense. After all the operator service and the installer a pretty different things to be included into a single binary.

**Comment by kkaempf** [comment]
Yes, we want (and need !) to have two different binaries. elemental-installer runs on the node, elemental-operator on the host cluster. They only have their "API" in common, as the installer needs to communicate with the operator during installation.

The common API is what initiated this card 😉

**Comment by davidcassany** [comment]
As we noted there was quite some relevant overlap between `elemental-operator register` command and `elemental-installer` (former `ros-installer`), the scope of this card essentially changed on adding the missing pieces to `elemental-operator register` to fully encompass the required functionality of what was meant to be `elemental-installer` as it seams to be the fastest path in order to achieve a functional stack. PR #38 is already aligned with this idea, follow up PRs will be required to handle free-from cloud-init data, cleanup unused logic from former `ros-installer` and any other eventual feature that was we might be missing from `ros-installer` days.

**Comment by davidcassany** [comment]
Since basic functional tests were already successful and the scope of this card changed quite a bit after using the `elemental-operator register` code base I consider this card to be done, essential parts from former `ros-installer` such as environmental variables mapping are already ported in `elemental-operator`.

After merging #45 keeping this card around make no sense.

For any missing features in `elemental-operator` follow up cards are going to be created.
