### ISSUE TITLE
Create a new entry point in elemental-operator server to download the registration config required on the client side

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-operator#73]
This issue is a result of the discussion in https://github.com/rancher/elemental-operator/pull/67#issuecomment-1190388225

Currently after adding a new machine registration crd into the management cluster a new registrationURL is dynamically created including the token required for this registration. To register a call of `elemental-operator register` is required on the client side. The client to perform such a registration requires the registrationURL and the associated certificate. To pass this two parameter we either use the command line `elemental-operator register --registration-url https://... --registration-ca-cert <path|certificate_string>` or by embedding this data into a config yaml file:

```yaml
elemental:
  registration:
    url: https://...
    ca-cert: <certificate string>
```

For convenience, currently, we can instruct the `elemental-operator` service to generate this yaml by an unauthenticated get request to the registration URL. As noted in https://github.com/rancher/elemental-operator/pull/67#issuecomment-1190388225 this is odd and most probably a bad practice.

Currently the registrationURL looks like `https://<hostname>/elemental/registration/<generatedtoken>`. To obtain this URL we could do something like:

 `kubectl get -n fleet-default machineregistration.elemental.cattle.io <machineregistrationname> -o yaml`
 
 where the resulting yaml includes `status.registrationURL`. Then using this URL to run an unauthenticated get request responds with the registration config yaml including this same URL and the associated certificate.
 
 Wouldn't it be better to implement a new entry point on the server side with something like
 
`http://<hostname>/elemental/registration/config/<machineregistrationname>`

that responds with

 ```yaml
elemental:
  registration:
    url: https://...
    ca-cert: <certificate string>
```

and, as suggested in the mentioned comment, simply return 403 for unauthenticated calls to the registrationURL?

**Comment by kkaempf** [comment]
This is to get rid of unauthenticated calls to the cluster, right ? 🤔 

> 
> Wouldn't it be better to implement a new entry point on the server side with something like
> 
> `http://<hostname>/elemental/registration/config/<machineregistrationname>`

Then why is this an `http` url and not an `https` url ?

**Comment by fgiudici** [comment]
Adding a couple of notes here, as looks to me here will live the discussion on how to rework the registration in the operator.
1. My guess is that the token in the url is some form of "authentication": in order to register with the operator, you have to know your token. Once you get the url, you can register there with the TPM hash: form that point the host is registered and allowed to become part of a cluster (assuming needed crds will be there) with no other requirement, so that token is the only protection to avoid unwanted hosts to register to the cluster.
2. If we don't consider 1., more realistic usage would be to have a single registration url for multiple hosts: so, you can have one ISO (or image) from which you can boot multiple hosts. Something proposed in #15 , which is now superseded by this issue.

**Comment by fgiudici** [comment]
This is superseded by #186 , closing
